version: "3.7"
services:

  rebrow:
      build: ./src
      ports:
       - "5001:5001"  
  
  redis:
      image: redis
      command: >
          --requirepass 123qwe
      ports:
       - "6379:6379"